---
title: "Composite Figures for Chapter 3 Juvenile CADO"
author: "Megan Delatte-Guidry"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PCA plots
Using these DESeq2 datasets for both PCA and Heatmaps

## PHASE I
```{r}
# get PCA data from DESeq2
pcaData <- plotPCA(global_vsdds_1,
                   intgroup = c("treatment"),
                   returnData = TRUE)

percentVar <- round(100 * attr(pcaData, "percentVar"))

pca1<- ggplot(pcaData,
       aes(x = PC1, y = PC2,
           fill = treatment))+   # fill by treatment
  geom_point(aes(fill=treatment), size = 5, alpha=.75, shape=21) +
  scale_fill_manual(values = c(
    control  = "#A29BAD",
    stress   = "#D29F13"
  )) +
  coord_fixed() +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) +
  labs(title = "Phase I global gene expression") +
  annotate("text", x = -10, y = 5, label = "Control", color = "#A29BAD", fontface="bold", size = 5) +
  annotate("text", x = 17, y = 20, label = "Stress", color = "#D29F13", fontface="bold", size = 5) +
  theme_minimal(base_size = 20) +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_blank(),
    plot.title=element_text(face = "bold", hjust = 0.5, size=12, color="black"),
    axis.title=element_text(face = "bold", size=12, color="black"),
    axis.text=element_text(size=12, color="black"), 
    axis.text.x = element_text(size = 12),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)
    #panel.background = element_rect(fill = alpha("white", 0.1))
    );pca1
```

## PHASE II
```{r}
# get PCA data from DESeq2
pcaData <- plotPCA(global_vsdds_2,
                   intgroup = c("treatment"),
                   returnData = TRUE)

percentVar <- round(100 * attr(pcaData, "percentVar"))

pca2 <- ggplot(pcaData,
       aes(x = PC1, y = PC2,
           fill = treatment)) +     # 
  geom_point(aes(fill=treatment), size = 5, alpha=.75, shape = 21, color = "black") +
  #coord_fixed() +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) +
  labs(title = "Phase II global gene expression") +
  annotate("text", x = -20, y = -23, label = "Control", color = "#A29BAD", fontface="bold", size = 5) +
  annotate("text", x = 27, y = 23, label = "Stress", color = "#D29F13", fontface="bold", size = 5) +
  annotate("text", x = -5, y = -15, label = "Naïve", color = "#6BA84C", fontface="bold", size = 5) +
  annotate("text", x = -10, y = 18, label = "Recovery", color = "#65A6E2", fontface="bold", size = 5) +
  scale_fill_manual(values = c(control="#A29BAD", stress ="#D29F13", naive= "#6BA84C", recovery= "#65A6E2")) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_blank(),
    plot.title=element_text(face = "bold", hjust = 0.5, size=16, color="black"),
    axis.title=element_text(face = "bold", size=12, color="black"),
    axis.text=element_text(size=12, color="black"), 
    axis.text.x = element_text(size = 12),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)
    #panel.background = element_rect(fill = alpha("white", 0.1))
    ); print(pca2)
```



# Heatmaps

## PHASE II
```{r}
#read in significant data sets for each treatment
sig_stress <- subset(res2_stress_ashr, padj<0.05)
sig_naive <- subset(res2_naive_ashr, padj<0.05)
sig_recovery <- subset(res2_recovery_ashr, padj<0.05)

#combine significant DEGs for all treatment contrasts
combine2 <- rbind(sig_stress, sig_naive, sig_recovery)
combine_list2 <- dm2[which(rownames(dm2) %in% rownames(combine2)),] #combined list from the original matrix so dupicates are removed 
summary(combine_list2)
#combine_rlog <- rlog(combine_list, blind=FALSE) #setting blind to FALSE takes into account levels and contrasts
vsd2 <- varianceStabilizingTransformation(combine_list2, blind=FALSE)
dim(combine_list2)
View(combine_list2)
```

limma removeBatchEffect()
```{r}
mat <- assay(vsd2)
mm <- model.matrix(~treatment, colData(vsd2))
mat <- limma::removeBatchEffect(mat, batch=vsd2$batch, design=mm)
assay(vsd2) <- mat
```

```{r}
library(ggplotify)
sig.num <- sum(combine2$padj <0.00001, na.rm=T) #set the p value cut off very low here, 1174 of 9060
sum(combine2$padj <0.00001, na.rm=T)
sum(combine2$padj!=0)
topVarGenes <- head(order(rowVars(assay(vsd2)),decreasing=TRUE),sig.num) #sort by decreasing sig
mat <- assay(vsd2)[ topVarGenes, ] #make an expression object
mat <- mat - rowMeans(mat) #difference in expression compared to average across all samples
#col.order <- c("CASE_J03", "CASE_J09", "CASE_J12", "CASE_J13")
#mat <- mat[,col.order]
df2 <- as.data.frame(colData(vsd2)[c("treatment")]) #make dataframe for column naming 

colfunc <- colorRampPalette(c("#7A9EA8", "white", "#C47A8A")) #make function for the color gradient 
ann_colors <- list( treatment= c(control="#A29BAD", stress ="#D29F13", naive= "#6BA84C", recovery= "#65A6E2"))
breakss <- c(-2, -1.9, -1.8, -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1, -.9, -.8, -.7, -.6, -.5, -.4, -.3, -.2, -.1, 0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2) #this looks very extra but this is how the colors in the heatmap were broken up 

heatmap2 <- pheatmap(mat, annotation_col=df2, annotation_colors=ann_colors, annotation_names_col = F, clustering_method = "average", 
         clustering_distance_rows="euclidean", show_rownames =FALSE, cluster_cols=F,
         show_colnames =F, breaks= breakss, color = colfunc(40), annotation_legend = F)

# create label for color bars 
# tab <- table(df2$treatment)
# labels <- names(tab)
# counts <- as.numeric(tab)
# centers <- cumsum(counts) - counts/2
# 
# label_df <- data.frame(
#   treatment = labels,
#   center = centers,
#   color = ann_colors$treatment[labels]
# )
# 
# str(label_df)
# 
# treatment_strip <- ggplot(label_df, aes(x = center, y = 1, label = treatment)) +
#   geom_text(aes(color = color), size = 5, fontface = "bold", show.legend = FALSE) +
#   scale_color_identity() +
#   scale_x_continuous(limits = c(0, ncol(mat))) +
#   # scale_x_continuous(
#   #   limits = c(1, ncol(mat)),   # <-- KEY CHANGE
#   #   expand = c(0, 0)) +
#   # coord_cartesian(clip = "off") +
#   theme_void() +
#   theme(
#     plot.margin = margin(0, 6, -6, 6)
#   )
# 
# h2 <- as.ggplot(heatmap2)
# 
# heatmap2_labeled <- treatment_strip / h2 +
#   plot_layout(heights = c(0.07, 1))

print(heatmap2)

# Export to PNG at a specific size
ggsave("../de_analysis/heatmaps/phase2_heatmap_glam.png", plot = heatmap2, width = 8, height =8, units = "in", dpi = 300)
```




# topGO plots
## PHASE I
```{r}
# read data
up <- read.csv("../de_analysis/topGO/data/enrichment_tables/phase1/p1_UP_genes_GO_enrichment.csv", header = TRUE)
down <- read.csv("../de_analysis/topGO/data/enrichment_tables/phase1/p1_DOWN_genes_GO_enrichment.csv", header = TRUE)

# Add regulation direction column
up$Regulation <- "Up-regulated"
down$Regulation <- "Down-regulated"
dim(up); dim(down)

#remove duplicate rows
up <- up[!duplicated(up$GO_Annotation), ]
down <- down[!duplicated(down$GO_Annotation), ]
dim(up); dim(down)

# Select top GO terms separately before combining
top_number = 5

top_up <- up %>%
  arrange(Fisher) %>%
  slice_head(n = top_number)

top_down <- down %>%
  arrange(Fisher) %>%
  slice_head(n = top_number)

# Combine the pre-filtered datasets
combined_data <- rbind(top_up, top_down)

# log transform 
combined_data$log10p <- -log10(combined_data$Fisher)

combined_data <- combined_data %>%
  mutate(Regulation = factor(Regulation, levels = c("Down-regulated", "Up-regulated"))) %>%
  arrange(Regulation, desc(Fisher)) %>%
  mutate(order = row_number())

#Prepare data for mirrored barplot
top_terms_mirror <- combined_data %>%
  mutate(log10p = ifelse(Regulation == "Down-regulated",
                                  -log10p,
                                  log10p))

#set colors for term text
term_colors = c(rep("#7A9EA8", top_number), rep("#C47A8A", top_number))

# Create mirrored barplot
topGO1 <- ggplot(top_terms_mirror, aes(x = reorder(Term, order),
                                    y = log10p,
                                    fill = Regulation)) +
  geom_col(width = 0.7, alpha = 0.8) +
  geom_hline(yintercept = 0, color = "black", linewidth = 0.8) +
  scale_fill_manual(values = c("Up-regulated" = "#C47A8A",
                                "Down-regulated" = "#7A9EA8")) +
  coord_flip() +
  theme_minimal() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom",
    legend.title = element_text(face = "bold"),
    axis.title = element_text(face = "bold"),
    axis.text = element_text(color = "black"),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 11, color = term_colors),
    plot.title=element_text(face = "bold", hjust =-3.5, size = 12, color="black")
  ) +
  scale_y_continuous(labels = abs) +
  labs(
    x = NULL,
    y = "-log10(Fisher p-value)",
    title = "Top Enriched GO Terms Among Significant DEGs",
    fill = "Regulation"
  );print(topGO1)
```


# Volcano plots 
## PHASE I

```{r}
deg1_clean <- read.csv("../de_analysis/outputs/p1_DEGs.csv")

# Create a basic volcano plot with adjusted p-values (to account for multiple hypothesis testing)
vol_str1 <- ggplot(data = deg1_clean, aes(x = log2FoldChange, y = -log10(padj), fill = diffexpressed))  +
  #add threshold lines (these are mostly arbitrarily chosen)
  geom_vline(xintercept = c(-0.8, 0.8), col = "gray", linetype = 'dashed') +
  #chose a pretty stringent p-value cut off 
  geom_hline(yintercept = -log10(0.001), col = "gray", linetype = 'dashed') +
  geom_point(pch=21, size = 3) +
  annotate("text", x = -10, y = 10, label = "Downregulated", color = "#7A9EA8", size = 6) +
  annotate("text", x = 10, y = 10, label = "Upregulated", color = "#C47A8A", size = 6) +
  # to set the colours of our variable
  scale_fill_manual(values = c("#7A9EA8", "grey", "#C47A8A")) +
                     # to set the labels in case we want to overwrite the categories from the dataframe (UP, DOWN, NO)
                     #labels = c("Downregulated", "Not significant", "Upregulated")) #removed legend
  labs(title = "Phase I Differential Expression") +
  # Biostatsquid theme
  theme_set(theme_classic(base_size = 12) +
              theme(
              axis.title.y = element_text(face = "bold",
                                          margin = margin(0,20,0,0),
                                          size = rel(1.1),
                                          color = 'black'),
              axis.title.x = element_text(hjust = 0.5,
                                          face = "bold",
                                          margin = margin(20,0,0,0),
                                          size = rel(1.1),
                                          color = 'black'),
              plot.title=element_text(face = "bold", hjust = 0.5, size = 12, color="black"),
              legend.position = "none"
              #legend.title = element_blank()
            )); print(vol_str1)
```


## PHASE II
```{r}
# read in data for plots
deg2_str_clean <- read.csv("../volcano_plots/outputs/PHASE2_STRESS_volcano_plot_data.csv")
deg2_rec_clean <- read.csv("../volcano_plots/outputs/PHASE2_RECOVERY_volcano_plot_data.csv")
deg2_nai_clean <- read.csv("../volcano_plots/outputs/PHASE2_NAIVE_volcano_plot_data.csv")

# PHASE 2 - STRESS
vol_str2 <- ggplot(data = deg2_str_clean, aes(x = log2FoldChange, y = -log10(padj), fill = diffexpressed))  +
  #add threshold lines (these are mostly arbitrarily chosen)
  geom_vline(xintercept = c(-0.8, 0.8), col = "gray", linetype = 'dashed') +
  #chose a pretty stringent p-value cut off 
  geom_hline(yintercept = -log10(0.001), col = "gray", linetype = 'dashed') +
  geom_point(pch=21, size = 3) +
  annotate("text", x = -10, y = 10, label = "Downregulated", color = "#7A9EA8", size = 6) +
  annotate("text", x = 10, y = 10, label = "Upregulated", color = "#C47A8A", size = 6) +
  annotate("text", x= -20, y= 28, label = "Stress", size = 10) +
  # to set the colours of our variable
  scale_fill_manual(values = c("#7A9EA8", "grey", "#C47A8A")) 
                     # to set the labels in case we want to overwrite the categories from the dataframe (UP, DOWN, NO)
                     #labels = c("Downregulated", "Not significant", "Upregulated")) #removed legend
  # Biostatsquid theme
  theme_set(theme_classic(base_size = 20) +
              theme(
              axis.title.y = element_text(face = "bold",
                                          margin = margin(0,20,0,0),
                                          size = rel(1.1),
                                          color = 'black'),
              axis.title.x = element_text(hjust = 0.5,
                                          face = "bold",
                                          margin = margin(20,0,0,0),
                                          size = rel(1.1),
                                          color = 'black'),
              plot.title = element_text(hjust = 0.5),
              legend.position = "none"
              #legend.title = element_blank()
            ))
  
# PHASE 2 - RECOVERY
vol_rec2 <- ggplot(data = deg2_rec_clean, aes(x = log2FoldChange, y = -log10(padj), fill = diffexpressed))  +
  #add threshold lines (these are mostly arbitrarily chosen)
  geom_vline(xintercept = c(-0.8, 0.8), col = "gray", linetype = 'dashed') +
  #chose a pretty stringent p-value cut off 
  geom_hline(yintercept = -log10(0.001), col = "gray", linetype = 'dashed') +
  geom_point(pch=21, size = 3) +
  annotate("text", x = -10, y = 10, label = "Downregulated", color = "#7A9EA8", size = 6) +
  annotate("text", x = 10, y = 10, label = "Upregulated", color = "#C47A8A", size = 6) +
  annotate("text", x= -20, y= 28, label = "Stress", size = 10) +
  # to set the colours of our variable
  scale_fill_manual(values = c("#7A9EA8", "grey", "#C47A8A")) 
                     # to set the labels in case we want to overwrite the categories from the dataframe (UP, DOWN, NO)
                     #labels = c("Downregulated", "Not significant", "Upregulated")) #removed legend
  # Biostatsquid theme
  theme_set(theme_classic(base_size = 20) +
              theme(
              axis.title.y = element_text(face = "bold",
                                          margin = margin(0,20,0,0),
                                          size = rel(1.1),
                                          color = 'black'),
              axis.title.x = element_text(hjust = 0.5,
                                          face = "bold",
                                          margin = margin(20,0,0,0),
                                          size = rel(1.1),
                                          color = 'black'),
              plot.title = element_text(hjust = 0.5),
              legend.position = "none"
              #legend.title = element_blank()
            ))
  
# PHASE 2 - NAIVE
vol_nai2 <- ggplot(data = deg2_nai_clean, aes(x = log2FoldChange, y = -log10(padj), fill = diffexpressed))  +
  #add threshold lines (these are mostly arbitrarily chosen)
  geom_vline(xintercept = c(-0.8, 0.8), col = "gray", linetype = 'dashed') +
  #chose a pretty stringent p-value cut off 
  geom_hline(yintercept = -log10(0.001), col = "gray", linetype = 'dashed') +
  geom_point(pch=21, size = 3) +
  annotate("text", x = -10, y = 10, label = "Downregulated", color = "#7A9EA8", size = 6) +
  annotate("text", x = 10, y = 10, label = "Upregulated", color = "#C47A8A", size = 6) +
  annotate("text", x= -20, y= 28, label = "Stress", size = 10) +
  # to set the colours of our variable
  scale_fill_manual(values = c("#7A9EA8", "grey", "#C47A8A")) 
                     # to set the labels in case we want to overwrite the categories from the dataframe (UP, DOWN, NO)
                     #labels = c("Downregulated", "Not significant", "Upregulated")) #removed legend
  # Biostatsquid theme
  theme_set(theme_classic(base_size = 20) +
              theme(
              axis.title.y = element_text(face = "bold",
                                          margin = margin(0,20,0,0),
                                          size = rel(1.1),
                                          color = 'black'),
              axis.title.x = element_text(hjust = 0.5,
                                          face = "bold",
                                          margin = margin(20,0,0,0),
                                          size = rel(1.1),
                                          color = 'black'),
              plot.title = element_text(hjust = 0.5),
              legend.position = "none"
              #legend.title = element_blank()
            ))
```




# Venn Diagram
## PHASE II
```{r}
# install.packages("ggVennDiagram")
# install.packages("ggplot2")

library(ggVennDiagram)
library(ggplot2)

# Create unique element IDs for each region
stress_only      <- paste0("S", 1:542)
recovery_only    <- paste0("R", 1:268)
naive_only       <- paste0("N", 1:324)

stress_recovery  <- paste0("SR", 1:186)
stress_naive     <- paste0("SN", 1:4)
recovery_naive   <- paste0("RN", 1:122)

all_three        <- paste0("SRN", 1:22)

# Build list
venn_list <- list(
  Recovery = c(recovery_only, stress_recovery, recovery_naive, all_three),
  Naïve    = c(naive_only, stress_naive, recovery_naive, all_three),
  Stress   = c(stress_only, stress_recovery, stress_naive, all_three)
)

ggVennDiagram(venn_list, label = "count") +
  scale_fill_gradient(low = "white", high = "white") +
  scale_color_manual(values = c("#6FA8DC", "#6AA84F", "#D8A028")) +
  theme(
    text = element_text(family = "Helvetica", face = "bold", size = 14),
    legend.position = "none"
  )
```




# COMPOSITE FIGURES

## PHASE I 

```{r}
top_design <- "
AAB
"
top_row <- vol_str1 + pca1 +
  plot_layout(design = top_design)

ge_phase1 <- top_row / free(topGO1) +
  plot_annotation(tag_levels = "a", tag_suffix = ")")&
  theme(plot.tag = element_text(size = 20, face = "bold"))
print(ge_phase1)
# Export to PNG at a specific size
ggsave("../manuscript_figures/main/Figure3_Phase1_DEG.png", plot = ge_phase1, width = 10, height =8, units = "in", dpi = 300)
```

## PHASE II

```{r}
library(ggplot2)
library(patchwork)
library(png)
library(grid)

getwd()
# Load your PNG
vd <- readPNG("../de_analysis/venn_diagrams/venn_diagram_w_title.png")
ht <- readPNG("../de_analysis/heatmaps/phase2_heatmap_glam_labeled_w_title.png")
pd <- readPNG("images/path_diagram_w_titles.png")

# Convert each PNG to a ggplot object
vd <- ggplot() +
  annotation_raster(vd, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  theme_void()
ht <- ggplot() +
  annotation_raster(ht, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  theme_void()
pd <- ggplot() +
  annotation_raster(pd, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  theme_void()
```

```{r}
# Combine with image using patchwork
#ge_phase2 <- pca2 | vd | ht

phase2_design <- "
AAABBCCCC
AAABBCCCC
DDDDDCCCC
DDDDDCCCC
"

ge_phase2 <- (pca2 | vd | ht | pd) +
  plot_layout(design = phase2_design) +
  plot_annotation(tag_levels = "a", tag_suffix = ")") &
  theme(plot.tag = element_text(size = 20, face = "bold"))
print(ge_phase2)

# Export to PNG at a specific size
ggsave("../manuscript_figures/main/Figure4_Phase2_DEG.png", plot = ge_phase2, width = 16, height =8, units = "in", dpi = 300)
```

